### PR TITLE
Work done for Team 1

### PR DESCRIPTION
**Pull request by davadeola**
In this branch, I have integrated the login flow, the bottom navigation, the message screens and the mentor list screen and the chat screen

### CODE REVIEW

**Comment by peculiaruc** [comment]
Kindly fix the errors spotted by Codacy

**Comment by peculiaruc** [comment]
Kindly schedule a meeting with me. to solve this problem today

**Comment by davadeola** [comment]
Could I schedule one now?

**Comment by davadeola** [comment]
meet.google.com/fuy-dguc-axh

**Comment by peculiaruc** [comment]
Meet – fuy-dguc-axh (google.com) <https://meet.google.com/fuy-dguc-axh> I
am in

**Pull request closed without merging**
